#!/usr/bin/env bash
#
# dev-setup.sh - generate Config/Signing.local.xcconfig so you can build and run Cotabby locally.
#
# Cotabby's project.yml does not hardcode an Apple team, so any contributor can build the repo.
# To launch the signed app from Xcode you supply your own team id once. This script detects it
# from your Apple Development signing certificate and writes the gitignored
# Config/Signing.local.xcconfig.
#
# Usage:
#   scripts/dev-setup.sh                              # auto-detect your team id
#   DEVELOPMENT_TEAM=XXXXXXXXXX scripts/dev-setup.sh  # set it explicitly, skip detection
#
# Kept compatible with the macOS system bash (3.2): no mapfile, associative arrays, or `${x^^}`.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
local_xcconfig="$repo_root/Config/Signing.local.xcconfig"

if [ -f "$local_xcconfig" ]; then
  echo "Config/Signing.local.xcconfig already exists:"
  sed 's/^/  /' "$local_xcconfig"
  echo
  echo "Edit it directly, or delete it and re-run to regenerate."
  exit 0
fi

# Print the Team ID (subject OU) of every Apple Development certificate, one per line.
# The "(...)" in the certificate name is a per-developer id, NOT the team id, so the OU is read
# from the certificate itself.
detect_team_ids() {
  local pem line cert
  pem="$(security find-certificate -a -p -c "Apple Development" 2>/dev/null || true)"
  [ -n "$pem" ] || return 0
  cert=""
  while IFS= read -r line; do
    cert="${cert}${line}"$'\n'
    if [ "$line" = "-----END CERTIFICATE-----" ]; then
      printf '%s' "$cert" \
        | openssl x509 -noout -subject -nameopt sep_multiline 2>/dev/null \
        | sed -n 's/^[[:space:]]*OU=//p' || true
      cert=""
    fi
  done <<< "$pem"
}

team="${DEVELOPMENT_TEAM:-}"

if [ -z "$team" ]; then
  ids="$(detect_team_ids | sort -u | sed '/^$/d' || true)"
  count="$(printf '%s' "$ids" | grep -c . || true)"

  if [ -z "$ids" ]; then
    echo "No 'Apple Development' signing certificate found."
    echo
    echo "Add your Apple ID in Xcode under Settings > Accounts (a free account works), let Xcode"
    echo "create a development certificate, then re-run this script. Or set the team explicitly:"
    echo "  DEVELOPMENT_TEAM=XXXXXXXXXX scripts/dev-setup.sh"
    exit 1
  fi

  if [ "$count" -gt 1 ]; then
    echo "Found more than one development team:"
    printf '%s\n' "$ids" | sed 's/^/  /'
    echo
    echo "Re-run with the one you want:"
    echo "  DEVELOPMENT_TEAM=XXXXXXXXXX scripts/dev-setup.sh"
    exit 1
  fi

  team="$ids"
fi

mkdir -p "$(dirname "$local_xcconfig")"
cat > "$local_xcconfig" <<EOF
// Generated by scripts/dev-setup.sh. Gitignored. Safe to edit or delete.
// Your Apple Development team id, used to sign local builds.
DEVELOPMENT_TEAM = $team

// Optional: uncomment and set if your personal team rejects the shared dev bundle id
// (Xcode: "Failed to register bundle identifier"). Gives the "Cotabby Dev" build its own id.
// COTABBY_DEV_BUNDLE_ID = com.yourname.tabby.dev
EOF

echo "Wrote $local_xcconfig"
echo "  DEVELOPMENT_TEAM = $team"
echo
echo "Next: open Cotabby.xcodeproj, select the \"Cotabby Dev\" scheme, and run."
